#!/bin/bash

# Ensure apache2 service is installed and running
puppet resource package apache2 ensure=installed
puppet resource service apache2 ensure=running enable=true

# Remove and recreate the research directory
puppet resource file /tmp/5616957y/research ensure=absent force=true
puppet resource file /tmp/5616957y/research ensure=directory

# Clone the repository
git clone https://github.com/22050005/5616957y_op_repo.git /tmp/5616957y/research

# Copy the new index.html file
puppet resource file /var/www/html/index.html ensure=file source=/tmp/5616957y/research/5616957y_index.html
